import { useState } from "react";

import Button from "../components/button";
import Icon, { type IconName } from "../components/icon";
import Input from "../components/input";
import Logo from "../components/logo";

export default function Login({ onLogin }: { onLogin: () => void }) {
  const [show, setShow] = useState(false);
  return <div className="relative min-h-screen overflow-hidden bg-[#FAF7F0]"><div className="absolute -left-24 -top-24 h-96 w-96 rounded-full bg-[#EAF2FF]" /><div className="absolute -bottom-40 -right-20 h-[500px] w-[500px] rounded-full bg-[#F4EFE5]" /><div className="relative grid min-h-screen grid-cols-[1fr_560px]">
    <div className="flex flex-col justify-center px-24"><Logo /><h1 className="mt-12 max-w-xl text-[42px] font-semibold leading-[1.25] tracking-[-.03em] text-[#173B70]">จัดการคลังสินค้า<br />และยอดขายได้ง่ายขึ้น</h1><p className="mt-5 max-w-lg text-[17px] leading-8 text-[#5D6878]">ระบบบริหารสินค้าสำหรับธุรกิจ ที่ช่วยให้การเช็กสต็อก บันทึกยอดขาย และดูรายงานเป็นเรื่องง่าย</p><div className="mt-10 grid max-w-lg grid-cols-3 gap-4">{[["box", "สต็อกแม่นยำ"], ["cart", "ขายได้รวดเร็ว"], ["report", "รายงานชัดเจน"]].map(x => <div key={x[1]} className="rounded-xl bg-white/80 p-4 shadow-sm"><Icon name={x[0] as IconName} className="text-[#2457A6]" /><p className="mt-3 text-[13px] font-medium">{x[1]}</p></div>)}</div></div>
    <div className="flex items-center bg-white px-16 shadow-[-20px_0_60px_rgba(23,59,112,.06)]"><form onSubmit={(e) => { e.preventDefault(); onLogin() }} className="w-full"><div className="mb-10 grid h-14 w-14 place-items-center rounded-2xl bg-[#2457A6] text-white shadow-lg shadow-blue-200"><Icon name="user" size={27} /></div><h2 className="text-[30px] font-semibold text-[#1F2937]">เข้าสู่ระบบ</h2><p className="mt-2 text-[15px] text-[#6B7280]">กรอกข้อมูลเพื่อเข้าสู่ระบบ StockWise</p><div className="mt-8 space-y-5"><Input label="ชื่อผู้ใช้งาน" icon="user" placeholder="กรอกชื่อผู้ใช้งาน" /><label className="block"><span className="mb-2 block text-[14px] font-medium">รหัสผ่าน</span><span className="relative block"><Icon name="lock" size={19} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#7B8492]" /><input type={show ? "text" : "password"} placeholder="กรอกรหัสผ่าน" className="h-12 w-full rounded-lg border border-[#DDE1E7] pl-11 pr-12 outline-none focus:border-[#2457A6] focus:ring-3 focus:ring-blue-100" /><button type="button" onClick={() => setShow(!show)} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-[#6B7280]" aria-label={show ? "ซ่อนรหัสผ่าน" : "แสดงรหัสผ่าน"}><Icon name="eye" size={20} /></button></span></label></div><div className="mt-4 flex justify-between text-[13px]"><label className="flex items-center gap-2"><input type="checkbox" className="accent-[#2457A6]" /> จดจำฉันไว้</label><button type="button" className="font-medium text-[#2457A6]">ลืมรหัสผ่าน?</button></div><Button type="submit" className="mt-8 h-12 w-full">เข้าสู่ระบบ</Button><p className="mt-8 text-center text-[12px] text-[#9CA3AF]">© 2025 StockWise Inventory System · Version 2.4</p></form></div>
  </div></div>;
}